language: go

go:
  - 1.8.x

env:
  global:
  - secure: "NzoMDrIBRVR1vI7/FQFJsJ1DLyVAi+0lQHoiMhqUGX4rvwfB3oYJm56sMYh7IucdhQi4kMqsDLXWbbz6T2IKxuc+c7+0aqW8gRGE83LEUwglbsj/V0Vj1+6AyfGDv2wETdZFIx7GDb1KrUs4WdbqmwnESw4ykjxeRpm/6GbOuyQ="
  - secure: "PRni5+aaGjLCirIYm+8AkHohcd0dOgTp/Bh/8FF6DgmKNJZUsD9qYeBF+4qdQjLxHfPC3iesDSci3NwUzXTQiDklR0TmFDesz2R2Yw6bgLQk0fXhrZEiBGlIYUn6sRlFk8wK1mg8y9OPwW3wOc8IJ1LUgBVoqC3+mrzjH8zPpmM="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y lftp

install:
  - go get github.com/spf13/hugo

script: hugo
script: 
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
after_success:
  - .travis/upload.sh "$USERNAME" "$PASSWORD"
