language: go

go:
  - 1.4.1

before_install:
  - openssl aes-256-cbc -K $encrypted_6193e035b232_key -iv $encrypted_6193e035b232_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d

install:
  - go get -u -v github.com/spf13/hugo

script: hugo

after_success:
  - eval $(ssh-agent)
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - cp CNAME public/CNAME
  - cd public
  - git init
  - git config user.name "Travis-CI"
  - git config user.email "travis@nodemeatspace.com"
  - git add .
  - git commit -m "Deployed to Github Pages"
  - git push --force --quiet "git@github.com:jurkan/acbad.git" master:gh-pages
