language: go

go:
  - 1.4.1

env:
  global:
  - secure: NlZ0Uh9vyrSvIhwZ+pDbXo5HffTNiRiUpjhfvZVrM42PIPVl4mdEOJHAIv1N+HDLoXxBX9a0Kmc1r5DrPC+4NxMPZD2Ey8mpXWwae1x+3yWwxPOcipac8/tQXZtHoScxJfVIcf8zOvA7zRb4PAzTn+s/wjuXPkkPyZX5QUp2Tqk=
  - secure: DQlHjUcDuhIWW4R8C4R4fvsAeE37G1U64oate9zzdjb9NoYXLG7w2ATLBtkFUMfp7MYITj0Cs0hYBDnlkePvox9/762Cqsdq7CUkOWiINAnjMP2isbd+/UCBP7W28RuyVUNcuoxyPvjcIaBGyqDB71lZvIYsYJeDU+GAMCqXdXI=

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y lftp

install:
  - go get github.com/spf13/hugo

script: hugo

after_success:
  - .travis/upload.sh "$USERNAME" "$PASSWORD"
