baseurl: "http://aero-club.eu/"
languageCode: "de-de"
title: "Aero-Club Baden-Baden e.V."

params:
  calltoaction: "/mitmachen/"
  description: "Die offizielle Website des Segelflug und Luftsportvereins Aero-Club Baden-Baden e.V."

permalinks:
  news: /:slug/

menu:
  main:
    - Name: "Über uns"
      Weight: 10
      Identifier: "ueberuns"
      URL: "/ueberuns/"
    - Name: "Verein"
      Weight: 0
      Identifier: "verein"
      URL: "/verein/"
      Parent: "ueberuns"
    - Name: "Presseberichte"
      Weight: 10
      Identifier: "presseberichte"
      URL: "/presseberichte/"
      Parent: "ueberuns"
    - Name: "Flugzeugpark"
      Weight: 20
      Identifier: "flugzeugpark"
      URL: "/flugzeugpark/"
      Parent: "ueberuns"
    - Name: "Flugplatz"
      Weight: 30
      Identifier: "flugplatz"
      URL: "http://www.flugplatz-baden-oos.de"
      Parent: "ueberuns"
    - Name: "Gaststätte"
      Weight: 40
      Identifier: "looping"
      URL: "/looping/"
      Parent: "ueberuns"
    - Name: "Mitmachen"
      Weight: 20
      Identifier: "mitmachen"
      URL: "/mitmachen/"
    - Name: "Ausbildung"
      Weight: 0
      Identifier: "ausbildung"
      URL: "/ausbildung/"
      Parent: "mitmachen"
    - Name: "Gebühren"
      Weight: 10
      Identifier: "preise"
      URL: "/preise/"
      Parent: "mitmachen"

    - Name: "Aktuelles"
      Weight: 30
      Identifier: "aktuelles"
      URL: "/news/"

    - Name: "News"
      Weight: 10
      Identifier: "news"
      URL: "/news/"
      Parent: "aktuelles"

    - Name: "Wetter"
      Weight: 20
      Identifier: "wetter"
      URL: "/wetter/"
      Parent: "aktuelles"

    - Name: "OLC"
      Weight: 30
      Identifier: "olc"
      URL: "/olc/"
      Parent: "aktuelles"                          

    - Name: "Kontakt"
      Weight: 40
      Identifier: "kontakt"
      URL: "/kontakt/"
