baseurl: "http://aero-club.eu/"
languageCode: "de-de"
title: "Aero-Club Baden-Baden e.V."

params:
  calltoaction: "/mitmachen/"
  description: "Die offizielle Website des Segelflug und Luftsportvereins Aero-Club Baden-Baden e.V."

permalinks:
  news: /:slug/

menu:
  main:
    - Name: "Über uns"
      Weight: 10
      Identifier: "ueberuns"
      URL: "/ueberuns/"
    - Name: "Presseberichte"
      Weight: 0
      Identifier: "presseberichte"
      URL: "/presseberichte/"
      Parent: "ueberuns"
    - Name: "Flugzeugpark"
      Weight: 10
      Identifier: "flugzeugpark"
      URL: "/flugzeugpark/"
      Parent: "ueberuns"
    - Name: "Gaststätte"
      Weight: 20
      Identifier: "looping"
      URL: "/looping/"
      Parent: "ueberuns"
    - Name: "Mitmachen"
      Weight: 20
      Identifier: "mitmachen"
      URL: "/mitmachen/"
    - Name: "Ausbildung"
      Weight: 0
      Identifier: "ausbildung"
      URL: "/ausbildung/"
      Parent: "mitmachen"
    - Name: "Gebühren"
      Weight: 10
      Identifier: "preise"
      URL: "/preise/"
      Parent: "mitmachen"
    - Name: "News"
      Weight: 30
      Identifier: "news"
      URL: "/news/"
    - Name: "Kontakt"
      Weight: 40
      Identifier: "kontakt"
      URL: "/kontakt/"
