baseurl: "http://aero-club.eu/"
languageCode: "de-de"
title: "Aero-Club Baden-Baden e.V."

params:
  calltoaction: "/mitmachen/"

permalinks:
  news: /:slug/

menu:
  main:
    - Name: "Über uns"
      Weight: 10
      Identifier: "ueberuns"
      URL: "/ueberuns/"
    - Name: "Flugzeugpark"
      Weight: 0
      Identifier: "flugzeugpark"
      URL: "/flugzeugpark/"
      Parent: "ueberuns"
    - Name: "Test"
      Weight: 10
      Identifier: "test"
      URL: "/test/"
      Parent: "ueberuns"

    - Name: "Mitmachen"
      Weight: 20
      Identifier: "mitmachen"
      URL: "/mitmachen/"
    - Name: "Preise"
      Weight: 0
      Identifier: "preise"
      URL: "/preise/"
      Parent: "mitmachen"

    - Name: "News"
      Weight: 30
      Identifier: "news"
      URL: "/news/"
    - Name: "Kontakt"
      Weight: 40
      Identifier: "kontakt"
      URL: "/kontakt/"
