baseurl: "http://aero-club.eu/"
languageCode: "de-de"
title: "Aero-Club Baden-Baden e.V."

params:
  calltoaction: "/mitmachen/"
  description: "Die offizielle Website des Segelflug und Luftsportvereins Aero-Club Baden-Baden e.V."

permalinks:
  news: /:slug/

menu:
  main:
    - Name: "Über uns"
      Weight: 10
      Identifier: "ueberuns"
      URL: "/ueberuns/"
    - Name: "Verein"
      Weight: 10
      Identifier: "verein"
      URL: "/verein/"
      Parent: "ueberuns"
    - Name: "Flugzeugpark"
      Weight: 20
      Identifier: "flugzeugpark"
      URL: "/flugzeugpark/"
      Parent: "ueberuns"
    - Name: "Gaststätte"
      Weight: 30
      Identifier: "looping"
      URL: "/looping/"
      Parent: "ueberuns"
    - Name: "Mitmachen"
      Weight: 20
      Identifier: "mitmachen"
      URL: "/mitmachen/"
    - Name: "Ausbildung"
      Weight: 10
      Identifier: "ausbildung"
      URL: "/ausbildung/"
      Parent: "mitmachen"
    - Name: "Gebühren"
      Weight: 20
      Identifier: "preise"
      URL: "/preise/"
      Parent: "mitmachen"

    - Name: "Aktuelles"
      Weight: 30
      Identifier: "aktuelles"
      URL: "/news/"
    - Name: "News"
      Weight: 10
      Identifier: "news"
      URL: "/news/"
      Parent: "aktuelles"
    - Name: "Veranstaltungen"                             
      Weight: 20                                 
      Identifier: "events"                       
      URL: "/events/"                            
      Parent: "aktuelles"                              
    - Name: "Presseberichte"
      Weight: 30
      Identifier: "presseberichte"
      URL: "/presseberichte/"
      Parent: "aktuelles"
    - Name: "Wettbewerb"
      Weight: 40
      Identifier: "wettbewerb"
      URL: "/wettbewerb/"
      Parent: "aktuelles"
    - Name: "Wetter"
      Weight: 50
      Identifier: "wetter"
      URL: "/wetter/"
      Parent: "aktuelles"      
    - Name: "Webcam"
      Weight: 60
      Identifier: "webcam"
      URL: "http://aero-club.eu/public/x-webcam/"
      Parent: "aktuelles"      



    - Name: "Archiv"
      Weight: 40
      Identifier: "archive"
      URL: "/archive/" 

    - Name: "News"
      Weight: 10
      Identifier: "archived_news"
      URL: "/archived_news/"
      Parent: "archive"


    - Name: "Veranstaltungen"                             
      Weight: 20                                 
      Identifier: "archived_events"                       
      URL: "/archived_events/"                            
      Parent: "archive"  

    - Name: "Presseberichte"
      Weight: 30
      Identifier: "presseberichte"
      URL: "/presseberichte/"
      Parent: "archive" 

    - Name: "Kontakt"
      Weight: 50
      Identifier: "kontakt"
      URL: "/kontakt/"
